let user = prompt (' Welcome to my site , Do you like Cras ?')
console.log( user )
let choice =prompt ( ' Bmw or Toyata ? ')
console.log( choice ) 
let series = prompt ( 'which series do you like ? ')
console.log ( series ) 
let type = prompt(' coupe or sedan ?')
console.log (type) 
let welcome =prompt ( ' WELCOME TO THE SITE ')
console.log ()
